org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.161.0+26.3

squaremap_api_version=1.4.0
opac_version=fabric-26.3-0.31.6
mod_version=1.0.1
maven_group=net.squaremarkers
archives_base_name=squaremarkers
